server:
  error:
    include-stacktrace: never

Spring:
  jpa:
    hibernate:
      ddl-auto: create
    datasource:
      url: jdbc:mysql://localhost:3306/schoolManagement-db?createDatabaseIfNotExist=true