server:
  error:
    include-stacktrace: never

Spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3307/schoolManagement-db?createDatabaseIfNotExist=true
    username: root
    password: